TRANSLATIONS = {
    "tabby": "смугастий кіт",
    "tiger_cat": "тигровий кіт",
    "Persian_cat": "перський кіт",
    "Siamese_cat": "сіамський кіт",
    "Egyptian_cat": "єгипетський кіт",
    "golden_retriever": "золотистий ретривер",
    "Labrador_retriever": "лабрадор-ретривер",
    "German_shepherd": "німецька вівчарка",
    "pug": "мопс",
    "beagle": "бігль",
    "tiger": "тигр",
    "lion": "лев",
    "leopard": "леопард",
    "cheetah": "гепард",
    "elephant": "слон",
    "bear": "ведмідь",
    "panda": "панда",
    "giant_panda": "велика панда",
    "monkey": "мавпа",
    "gorilla": "горила",
    "chimpanzee": "шимпанзе",
    "orangutan": "орангутан",
    "zebra": "зебра",
    "giraffe": "жираф",
    "horse": "кінь",
    "racehorse": "скаковий кінь",
    "fox": "лисиця",
    "wolf": "вовк",
    "rabbit": "кролик",
    "hare": "заєць",
    "mouse": "миша",
    "bird": "птах",
    "eagle": "орел",
    "owl": "сова",
    "parrot": "папуга",
    "penguin": "пінгвін",
    "ostrich": "страус",
    "goldfish": "золота рибка",
    "shark": "акула",
    "dolphin": "дельфін",
    "whale": "кит",
    "snake": "змія",
    "turtle": "черепаха",
    "frog": "жаба",
    "lizard": "ящірка",
    "crocodile": "крокодил",
    "alligator": "алігатор",
    "spider": "павук",
    "bee": "бджола",
    "butterfly": "метелик",
    "ladybug": "сонечко (комаха)",
    "cock": "півень",
    "hen": "курка",

    "espresso": "еспресо",
    "coffee": "кава",
    "cup": "чашка",
    "pizza": "піца",
    "hamburger": "гамбургер",
    "hotdog": "хот-дог",
    "burrito": "буріто",
    "taco": "тако",
    "French_loaf": "французький батон",
    "bagel": "бейгл",
    "pretzel": "крендель",
    "cheeseburger": "чізбургер",
    "orange": "апельсин",
    "lemon": "лимон",
    "banana": "банан",
    "apple": "яблуко",
    "pineapple": "ананас",
    "strawberry": "полуниця",
    "ice_cream": "морозиво",
    "chocolate_sauce": "шоколадний соус",
    "carbonara": "карбонара",
    "plate": "тарілка",
    "wine_bottle": "пляшка вина",
    "beer_bottle": "пляшка пива",
    "beer_glass": "келих пива",
    "water_bottle": "пляшка води",

    "sports_car": "спортивний автомобіль",
    "convertible": "кабріолет",
    "racer": "гоночний автомобіль",
    "car": "автомобіль",
    "minivan": "мінівен",
    "taxi": "таксі",
    "limousine": "лімузин",
    "bus": "автобус",
    "truck": "вантажівка",
    "pickup": "пікап",
    "tractor": "трактор",
    "motorcycle": "мотоцикл",
    "bicycle": "велосипед",
    "mountain_bike": "гірський велосипед",
    "train": "потяг",
    "airplane": "літак",
    "helicopter": "вертоліт",
    "ship": "корабель",
    "boat": "човен",
    "yacht": "яхта",
    "speedboat": "швидкісний катер",
    "submarine": "підводний човен",
    "parachute": "парашут",
    "gondola": "гондола",
    "snowmobile": "снігохід",
    "ambulance": "швидка допомога",
    "fire_engine": "пожежна машина",
    "police_van": "поліцейський фургон",

    "laptop": "ноутбук",
    "notebook": "ноутбук",
    "computer": "комп'ютер",
    "desktop_computer": "настільний комп'ютер",
    "monitor": "монітор",
    "screen": "екран",
    "keyboard": "клавіатура",
    "mouse": "комп'ютерна миша",
    "phone": "телефон",
    "cellular_telephone": "мобільний телефон",
    "smartphone": "смартфон",
    "iPod": "iPod",
    "television": "телевізор",
    "remote_control": "пульт дистанційного керування",
    "radio": "радіо",
    "microphone": "мікрофон",
    "camera": "фотоапарат",
    "digital_camera": "цифровий фотоапарат",
    "projector": "проектор",
    "printer": "принтер",
    "scanner": "сканер",
    "headphones": "навушники",
    "cassette_player": "касетний програвач",
    "CD_player": "CD-програвач",
    "joystick": "джойстик",
    "gamepad": "геймпад",

    "chair": "стілець",
    "table": "стіл",
    "desk": "письмовий стіл",
    "bed": "ліжко",
    "sofa": "диван",
    "couch": "кушетка",
    "lamp": "лампа",
    "wardrobe": "шафа",
    "bookcase": "книжкова шафа",
    "refrigerator": "холодильник",
    "stove": "плита",
    "oven": "духовка",
    "microwave": "мікрохвильова піч",
    "toaster": "тостер",
    "coffee_mug": "кавова чашка",
    "teapot": "чайник",
    "bottle": "пляшка",
    "bowl": "миска",
    "vase": "ваза",
    "clock": "годинник",
    "digital_clock": "електронний годинник",
    "pillow": "подушка",
    "blanket": "ковдра",
    "towel": "рушник",
    "shower_curtain": "душова завіса",
    "toilet_tissue": "туалетний папір",
    "soap_dispenser": "дозатор мила",
    "ladle": "черпак",
    "spatula": "лопатка",
    "cleaver": "сокира для м'яса",
    "pot": "каструля",
    "pan": "сковорода",
    "frying_pan": "сковорода",
    "wok": "вок",

    "sunglass": "сонцезахисні окуляри",
    "sunglasses": "сонцезахисні окуляри",
    "hat": "капелюх",
    "baseball": "бейсбольний м'яч",
    "basketball": "баскетбольний м'яч",
    "soccer_ball": "футбольний м'яч",
    "tennis_ball": "тенісний м'яч",
    "backpack": "рюкзак",
    "purse": "жіноча сумочка",
    "wallet": "гаманець",
    "umbrella": "парасолька",
    "bow_tie": "метелик (краватка)",
    "tie": "краватка",
    "jersey": "джерсі",
    "shoe": "черевик",
    "sandal": "сандалія",
    "boot": "чобіт",
    "sneaker": "кросівка",
    "mask": "маска",
    "helmet": "шолом",
    "glove": "рукавичка",
    "sock": "шкарпетка",
    "scarf": "шарф",
    "mitten": "рукавиця",
    "ring": "кільце",
    "necklace": "намисто",
    "watch": "наручний годинник",
    "wristwatch": "наручний годинник",

    "hammer": "молоток",
    "screwdriver": "викрутка",
    "saw": "пилка",
    "drill": "дриль",
    "wrench": "гайковий ключ",
    "ax": "сокира",
    "shovel": "лопата",
    "scissors": "ножиці",
    "pencil": "олівець",
    "pen": "ручка",
    "paintbrush": "пензель",
    "ruler": "лінійка",
    "paperclip": "скріпка",
    "stapler": "степлер",
    "nail": "цвях",
    "chain_saw": "бензопила",
    "power_drill": "електродриль",

    "piano": "піаніно",
    "guitar": "гітара",
    "acoustic_guitar": "акустична гітара",
    "electric_guitar": "електрогітара",
    "violin": "скрипка",
    "drum": "барабан",
    "flute": "флейта",
    "saxophone": "саксофон",
    "trumpet": "труба",
    "harp": "арфа",
    "organ": "орган",

    "dumbbell": "гантеля",
    "barbell": "штанга",
    "parallel_bars": "бруси",
    "horizontal_bar": "турнік",
    "punching_bag": "груша для боксу",
    "weight": "вага",
    "ski": "лижа",
    "snowboard": "сноуборд",
    "surfboard": "серф",
    "skateboard": "скейтборд",
    "parachute": "парашут",
    "golf_ball": "м'яч для гольфу",
    "ping-pong_ball": "м'яч для пінг-понгу",

    "tree": "дерево",
    "flower": "квітка",
    "rose": "троянда",
    "daisy": "ромашка",
    "mushroom": "гриб",
    "coral_reef": "коралові рифи",
    "rock": "камінь",
    "mountain": "гора",
    "volcano": "вулкан",
    "cliff": "скеля",
    "lakeside": "берег озера",
    "seashore": "морський берег",
    "beach": "пляж",
    "valley": "долина",
    "forest": "ліс",

    "sunscreen": "сонцезахисний крем",
    "candle": "свічка",
    "bell_pepper": "болгарський перець",
    "balloon": "повітряна куля",
    "fountain": "фонтан",
    "castle": "замок",
    "church": "церква",
    "mosque": "мечеть",
    "palace": "палац",
    "prison": "в'язниця",
    "grocery_store": "продуктовий магазин",
    "library": "бібліотека",
    "barn": "сарай",
    "bookshop": "книгарня",
    "barbershop": "перукарня",
    "bakery": "пекарня",
    "torch": "факел",
    "candle": "свічка",
    "jigsaw_puzzle": "пазл",
    "crossword_puzzle": "кросворд",
    "maze": "лабіринт",
    "toyshop": "магазин іграшок",
}


def translate_label(label: str) -> str:
    if " " in label:
        parts = label.split(" ", 1)
        if len(parts) > 1:
            label = parts[1]

    translation = TRANSLATIONS.get(label)

    if translation:
        return f"{translation} ({label})"
    else:
        return label.replace("_", " ")


def get_translation(label: str, show_original: bool = True) -> str:
    if " " in label:
        parts = label.split(" ", 1)
        if len(parts) > 1:
            label = parts[1]

    translation = TRANSLATIONS.get(label)

    if translation:
        if show_original:
            return f"{translation} ({label})"
        else:
            return translation
    else:
        return label.replace("_", " ")
